apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
---
apiVersion: v1
kind: Secret
metadata:
  name: node-app-secrets
type: Opaque
data:
  # Add your base64 encoded secrets here
  # Example: DATABASE_URL: <base64-encoded-value> 